# §
#AstrideEarthCore by Dynmie
console: '&cOnly players can execute this command!'
noperms: '&cNo permission.'
#Fly
enablefly: 'Flying &aenabled'
disablefly: 'Flying &cdisabled'

#Handle ChatSystem
# %player% = player with prefix
# %message% = message
# %chatcolor% = chatcolor
# Color codes are allowed
# System EventHandler is set to NORMAL
chatsystem: true
chatformat: '&f%player% &7»&f %message%'
messageformat: '%chatcolor%%message%'

#Lobby?
lobby: false

#toggles
enabled: '&lenabled'
disabled: '&ldisabled'

slowtime: 2

#CannotCraft
CannotCraft: '&cYou cannot craft this item!'
PlayerOffline: '&cThat player is offline.'

KillAll: '&aKilled all entities'

ping: '&aYour ping:'

disabled-vanish: '&cYou have &ldisabled&c vanish.'
enabled-vanish: '&bYou have &lenabled&b vanish.'
#Handle joinleave vanish requires handle-joinleave to be set to true.
handle-joinleave-vanish: true

#Join and leave messages
handle-joinleave: true
joinmessage: ''
quitmessage: ''