name: Core
version: ${project.version}
main: me.dynmie.astrideearthcore.Main
depend: [Vault]
softdepend: [LuckPerms]
authors: [Astride Development]

commands:
  fly:
  gamemode:
    aliases: [gm]
    description: 'Changes your gamemode.'
  heal:
  feed:
  message:
    aliases: [msg, w, tell, whisper]
  reply:
    aliases: [r]
    description: 'Replies to a user you have messaged before.'
  flyspeed:
    description: 'Changes your fly speed.'
  walkspeed:
    description: 'Changes your walk speed.'
  kill:
  chat:
  sudo:
  nightvision:
    aliases: [nv]
  disguise:
    aliases: [mobkill]
    vanish:
  killall:
    aliases: [v, s]
  list:
  invsee:
    aliases: [inventory]
  freeze:
  teleport:
    aliases: [tp]
  tpall:
    aliases: [teleportall]
  tpask:
    aliases: [tpa]
  tpaccept:

permissions:
  astride.speed:
    description: Permission to change all of your speeds
    children:
      astride.walkspeed: true
      astride.flyspeed: true
  astride.vanish:
    children:
      astride.vanish.see: true
      astride.vanish.vanish: true
  astride.freeze:
    description: Permission to freeze players
  astride.freeze.exempt:
    description: Permission to be exempted from freezing
  astride.fly:
    description: Permission to fly
  astride.heal:
    description: Permission to heal
  astride.feed:
    description: Permission to feed
  astride.chat:
    description: Permission for chat commands
  astride.chat.format:
    description: Permission for chat formatting, eg/ italics, bold
  astride.chat.spy:
    description: Allows the player to spy chat messages.
  astride.kill:
    description: Permission to kill
  astride.gamemode:
    description: Permission for gamemode change
  astride.disguise:
    description: Permission for disguising
  astride.walkspeed:
    description: Permission to change your speed
  astride.flyspeed:
    description: Permission to change your speed
  astride.craftexempt:
    description: Permission for crafting exempt
  astride.sudo:
    description: Permission to use sudo command
  astride.kill.all:
    description: Permission to kill all mobs
  astride.vanish.see:
    description: Permission to see vanished players
  astride.vanish.vanish:
    description: Permission to vanish
  astride.invsee:
    description: Permission to invsee
  astride.teleport:
    description: Permission to teleport
  astride.teleport.all:
    description: Permission to teleport everyone to your location
  astride.vanish.full:
    description: Permission to vanish from all players including staff
  astride.vanish.exempt:
    description: Permission to be exempted from fullvanish.